# Generated by Django 3.0.3 on 2020-04-03 09:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseId', models.IntegerField(blank=True, null=True)),
                ('course_code', models.CharField(default='xxxxx', max_length=5)),
                ('course_name', models.CharField(blank=True, max_length=30, null=True)),
                ('lab_included', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Timings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(default='Sunday', max_length=9)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entryNo', models.CharField(max_length=10, unique=True)),
                ('firstName', models.CharField(max_length=30)),
                ('lastName', models.CharField(max_length=30)),
                ('department', models.CharField(max_length=30)),
                ('year', models.CharField(max_length=10)),
                ('degree', models.CharField(max_length=30)),
                ('contact', models.BigIntegerField(unique=True)),
                ('emailId', models.CharField(max_length=100, unique=True)),
                ('userId', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userType', models.CharField(max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Faculties',
            fields=[
                ('facId', models.AutoField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=30)),
                ('lastName', models.CharField(max_length=30)),
                ('department', models.CharField(max_length=30)),
                ('designation', models.CharField(max_length=30)),
                ('contact', models.BigIntegerField(unique=True)),
                ('emailId', models.CharField(max_length=100, unique=True)),
                ('userId', models.OneToOneField(db_index=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CourseSlots',
            fields=[
                ('course_slot_id', models.AutoField(primary_key=True, serialize=False)),
                ('timing_list', models.ManyToManyField(to='dataccess.Timings')),
            ],
        ),
        migrations.CreateModel(
            name='CourseOffered',
            fields=[
                ('course_offered_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_year', models.CharField(max_length=4)),
                ('course_sem', models.BooleanField()),
                ('courseId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dataccess.Courses')),
                ('course_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='dataccess.Timings')),
                ('facId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dataccess.Faculties')),
            ],
        ),
    ]
