# Generated by Django 3.0.3 on 2020-04-10 16:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseOffered',
            fields=[
                ('course_offered_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_year', models.CharField(max_length=4)),
                ('course_sem', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseId', models.IntegerField(blank=True, null=True)),
                ('course_code', models.CharField(default='xxxxx', max_length=5)),
                ('course_name', models.CharField(blank=True, max_length=30, null=True)),
                ('lab_included', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Timings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(default='Sunday', max_length=9)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='TeachingAssistant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField(max_length=15, unique=True)),
                ('emailId', models.CharField(max_length=100)),
                ('entryNo', models.CharField(max_length=10, unique=True)),
                ('firstName', models.CharField(max_length=30)),
                ('lastName', models.CharField(max_length=30)),
                ('department', models.CharField(max_length=30)),
                ('course_offered', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dataccess.Courses')),
                ('userId', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entryNo', models.CharField(max_length=10, unique=True)),
                ('firstName', models.CharField(max_length=30)),
                ('lastName', models.CharField(max_length=30)),
                ('department', models.CharField(max_length=30)),
                ('year', models.CharField(max_length=10)),
                ('degree', models.CharField(max_length=30)),
                ('contact', models.CharField(max_length=20, unique=True)),
                ('emailId', models.CharField(max_length=100)),
                ('userId', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentCourseReg',
            fields=[
                ('course_reg_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_offered', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dataccess.CourseOffered')),
                ('studentId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dataccess.Students')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userType', models.CharField(max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Faculties',
            fields=[
                ('facId', models.AutoField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=30)),
                ('lastName', models.CharField(max_length=30)),
                ('department', models.CharField(max_length=30)),
                ('designation', models.CharField(max_length=30)),
                ('contact', models.CharField(max_length=100, unique=True)),
                ('emailId', models.CharField(max_length=100)),
                ('userId', models.OneToOneField(db_index=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CourseSlots',
            fields=[
                ('course_slot_id', models.AutoField(primary_key=True, serialize=False)),
                ('timing_list', models.ManyToManyField(to='dataccess.Timings')),
            ],
        ),
        migrations.AddField(
            model_name='courseoffered',
            name='courseId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dataccess.Courses'),
        ),
        migrations.AddField(
            model_name='courseoffered',
            name='course_slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='dataccess.CourseSlots'),
        ),
        migrations.AddField(
            model_name='courseoffered',
            name='facId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dataccess.Faculties'),
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('value', models.BooleanField(default=True)),
                ('studentReg', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dataccess.StudentCourseReg')),
            ],
            options={
                'unique_together': {('date', 'studentReg')},
            },
        ),
    ]
