# Generated by Django 3.0.3 on 2020-04-07 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataccess', '0002_teachingassistant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculties',
            name='contact',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='faculties',
            name='emailId',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='students',
            name='contact',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='emailId',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='teachingassistant',
            name='emailId',
            field=models.CharField(max_length=100),
        ),
    ]
