# Generated by Django 3.0.3 on 2020-04-07 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataccess', '0003_auto_20200407_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculties',
            name='contact',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
