# Generated by Django 3.0.3 on 2020-04-08 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataccess', '0004_auto_20200407_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseoffered',
            name='course_slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='dataccess.CourseSlots'),
        ),
    ]
