# Generated by Django 3.0.3 on 2020-04-08 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataccess', '0006_auto_20200408_0900'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentCourseReg',
            fields=[
                ('course_reg_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_offered', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dataccess.CourseOffered')),
                ('studentId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dataccess.Students')),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('value', models.BooleanField(default=True)),
                ('studentReg', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dataccess.StudentCourseReg')),
            ],
            options={
                'unique_together': {('date', 'studentReg')},
            },
        ),
    ]
