# Generated by Django 3.0.3 on 2020-04-08 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataccess', '0007_attendancerecord_studentcoursereg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='contact',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
