"""
Django settings for Attendance_System project.

Generated by 'django-admin startproject' using Django 3.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""
# import environ
# coding: utf-8
import os
from decouple import config
from pathlib import Path
from dj_database_url import parse as db_url

# # Build paths inside the project like this: os.path.join(BASE_DIR, ...)
# root = environ.Path(__file__) - 3  # get root of the project
# env = environ.Env()
# environ.Env.read_env()  # reading .env file

# SITE_ROOT = root()
# BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BASE_DIR = Path(__file__).parent

# # Quick-start development settings - unsuitable for production
# # See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# # SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = 'nz(*9&p4-$7oxg5n5ysk!7bx7*tb_*oes**a(d$6jtr(06ao3#'
# SECRET_KEY = env.str('SECRET_KEY')
SECRET_KEY = config('SECRET_KEY',default='nz(*9&p4-$7oxg5n5ysk!7bx7*tb_*oes**a(d$6jtr(06ao3#' )
# print()

# # SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = True
DEBUG = config('DEBUG', default=False, cast=bool)
TEMPLATE_DEBUG = config('TEMPLATE_DEBUG', default=False, cast=bool)
# DEBUG = env.bool('DEBUG', default=False)config('DEBUG', default=False, cast=bool)


ALLOWED_HOSTS = []


# # Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'dataccess',
    'attendance_management',
    'leaves_management',
    'reschedule_management',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Attendance_System.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Attendance_System.wsgi.application'


# # Database
# # https://docs.djangoproject.com/en/3.0/ref/settings/#databases
## For cloud Database this option 
# DATABASES = {'default':
#         env.db('DATABASE_URL')
#         config('DATABASE_URL',default='sqlite:///' + BASE_DIR.child('db.sqlite3'),cast=db_url)
#          }

# # DATABASES = {
# #     'default': {
# #         'ENGINE': 'django.db.backends.sqlite3',
# #         'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
# #     }
# # }

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': config('DATABASE_NAME',default='test'),
        'USER': config('DATABASE_USER'),
        'PASSWORD': config('DATABASE_PASSWORD'),
        'HOST': '',
        'PORT': '',
   }
}
 
# # Password validation
# # https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# # Internationalization
# # https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# # Static files (CSS, JavaScript, Images)
# # https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = '/static/'

# public_root = root.path('public/')
# MEDIA_ROOT = public_root('media')
# MEDIA_URL = env.str('MEDIA_URL', default='media/')
# STATIC_ROOT = public_root('static')
# STATIC_URL = env.str('STATIC_URL', default='static/')


# CACHES = {'default': env.cache('REDIS_CACHE_URL')}