# Generated by Django 3.0.3 on 2020-03-31 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_management', '0003_auto_20200331_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='userId',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='attendance_management.Users'),
        ),
    ]
